server:
  port: 8070
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    name: room
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice

  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl