server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    name: room
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice

  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: SH

#指定那个服务需要配置负载均衡的规则
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则

#开启饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients:
      - orderservice
      - userservice

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl