server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    name: room
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice

  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: SH
        ephemeral: false # 非临时实例
        #namespace: xxxxxxxxxx

#指定那个服务需要配置负载均衡的规则
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则

#开启饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients:
      - orderservice
      - userservice

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.xxstudy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

feign:
  httpclient:
    enabled: true
    max-connections: 300 #最大连接数
    max-connections-per-route: 100 #每个路径最大连接数 ，这些都需要根据服务器压测结果进行调整
  client:
    config:
      default:
        loggerLevel: FULL